version: '3.8'
 
services:
  nodejs:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
 
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'