version: '3.8'

services:
  king-5:
    image: david-5
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI:'mongodb://localhost:27017/test'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
